[package]
name = "mutspec"
version = "0.1.0"
authors = ["Michael Macias <michael.macias@stjude.org>"]

[dependencies]
clap = "2.32.0"
csv = "1.0.0"
handlebars = "1.0.0"
lazy_static = "1.0.2"
reqwest = "0.8.6"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
